### ISSUE TITLE
once conflicts if you have spatie/once installed

### ISSUE THREAD

**Issue by dbpolito** [pestphp/pest-plugin-global-assertions#1]
I know it's a hard problem to solve, just wanted to point here if in case someone gets ideas.

Maybe a config or a way to choose what to register globally?

PS: `spatie/once` is used by `laravel/nova` so this may happen more.

**Comment by owenvoke** [comment]
Interesting point, not sure we can do much about this though. 🤔 Perhaps we should just add a conflict in Composer?

I mean, technically this package isn't recommended and was pretty much only for the transition period between Pest 0.2 and 0.3. 🤷🏻

**Comment by dbpolito** [comment]
Yeah it was pretty easy for me to upgrade, just a few find / replaces and i created a few helpers myself that is used more like `assertEquals`.

Didn't know about `conflict` on `composer`, sounds a good/simple idea.

**Comment by owenvoke** [comment]
I'll do another release tomorrow maybe. Although unfortunately it'll still install v0.3.0

I can also add a notice to the docs maybe to flag this up as an issue.

**Comment by owenvoke** [comment]
I've updated the package so it now does the same as PHPUnit's functions. This is good in one way as now it checks to see if each of the functions has been declared already before registering them. Although the `spatie/once` conflict still is an issue.
